services:
  airflow:
    build:
      context: .
    ports:
      - 8080:8080
      - 8081:8081
    volumes:
      - ./airflow_base:/airflow_base
      - ./data-docker/dockerd-entrypoint.sh:/usr/local/bin/dockerd-entrypoint.sh
    privileged : true
    # restart: always
    networks :
      - airflow-devft-network

networks:
  airflow-devft-network:
    name: airflow-devft-network
  # container_server :
  #   image: docker:dind
  #   privileged : true
  #   restart: always