services:
  container-server :
    build : ./docker-server/.
    volumes :
      - ./pipe:/airflow_base/pipe
    privileged : true
    restart : always
    networks:
      - airflow-rtn-network

networks:
  airflow-rtn-network: