services:
  container-server :
    build : ./docker-server/.
    volumes :
      - ./Data:/airflow_base/Data
      - ./dags/Docker:/airflow_base/dags/Docker
    privileged : true
    restart : always
    networks:
      - airflow-rtn-network

networks:
  airflow-rtn-network: